export enum Authority {
  DOCTOR = 'ROLE_DOCTOR',
  NURSE = 'ROLE_NURSE',
  PARAMEDIC = 'ROLE_PARAMEDIC',
  PHARMACIST = 'ROLE_PHARMACIST',
  THERAPIST = 'ROLE_THERAPIST',
  CARER = 'ROLE_CARER',
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
}
