export enum Authority {
  DOCTOR = 'ROLE_DOCTOR',
  NURSE = 'ROLE_NURSE',
  PARAMEDIC = 'ROLE_PARAMEDIC',
  PHARMACIST = 'ROLE_PHARMACIST',
  THERAPIST = 'ROLE_THERAPIST',
  CARER = 'ROLE_CARER',
  ANGEL = 'ROLE_ANGEL',
  CHEMIST = 'ROLE_CHEMIST',
  TECHNICIAN = 'ROLE_TECHNICIAN',
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
}
