export enum PersonalDocumentType {
    PASSPORT = 'PASSPORT',
    LICENSE = 'LICENSE',
    GHANACARD = 'GOVERNMENT CARD',
    VOTERCARD = 'VOTER CARD',
    PASSPHOTO = 'PASSPORT PHOTO',
    DRIVER_LICENSE = 'DRIVER LICENSE',
    ID_CARD = 'ID CARD',
    BIRTH_CERTIFICATE = 'BIRTH CERTIFICATE',
    NHIS = 'NHIS',
    OTHER = 'OTHER'

}