export enum PersonalDocumentType {
  PASSPORT = 'PASSPORT',
  LICENSE = 'LICENSE',
  GHANACARD = 'GHANACARD',
  VOTERCARD = 'VOTERCARD',
  PASSPHOTO = 'PASSPHOTO',
  DRIVERLICENSE = 'DRIVERLICENSE',
  CERTIFICATE = 'CERTIFICATE',
  NHIS = 'NHIS',
  OTHER = 'OTHER',
}
